version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env:
      NODE_ENV: production
    healthcheck:
      command: ["curl", "-f", "http://localhost:3000/api"]
      interval: 30s
      timeout: 10s
      retries: 3
